services:
  - type: web
    name: restaurant-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_migrations.py && gunicorn --worker-class sync --workers 1 -b 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: BABEL_DEFAULT_LOCALE
        value: ar
      - key: USE_EVENTLET
        value: "0"
      - key: USE_EVENTLET_FOR_SERVER
        value: "0"
      - key: FLASK_APP
        value: app

databases:
  - name: restaurant-db
    databaseName: restaurant_system
    user: restaurant_user
